name: Purple Snake Generator
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Frnaxx
          outputs: github-contribution-grid-snake.svg
          color: "#8A2BE2" # رنگ بنفش
          direction: "b" # جهت مار

      - name: Push to Output
        uses: EndBug/[email protected]
        with:
          branch: "output"
          message: "Update Snake Animation"
